
services:
  - type: web
    name: micrositio-backend
    runtime: node
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    rootDir: backend
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_PATH
        value: /data/database.db
    disk:
      name: micrositio-db
      mountPath: /data
      sizeGB: 1
